version: '3.8'
services:
  nextjs:
    build:
      context: ./only-edu-mbbs
    ports:
      - "3000:3000"
    depends_on:
      - strapi
      - nodejs-api

  strapi:
    build:
      context: ./api
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: your_database_host
      DATABASE_PORT: your_database_port
      DATABASE_NAME: your_database_name
      DATABASE_USERNAME: your_database_username
      DATABASE_PASSWORD: your_database_password

  nodejs-api:
    build:
      context: ./nodeApi
    ports:
      - "8000:8000"
    depends_on:
      - strapi
