import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "../styles/globals.css";
import "../styles/normalize.css";
import Navbar from "@/modules/navbar";
import Footer from "@/modules/footer";
import { flattenAttributes, getStrapiData } from "@/utils/utils";
import MySideBar from "@/modules/navbar/components/Sidebar";

const inter = Ubuntu({
  subsets: ["cyrillic"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navData = await getStrapiData(
    "/api/global?populate[navigation][populate][links]=*&[populate][dropdown][populate][subMenuLinks][populate][university]=*"
  );

  return (
    <html lang="en">
      <body className={`bg-light dark:bg-dark  ${inter.className}`}>
        <div className="relative w-full h-full">
          <Navbar navigation={navData.navigation} dropdown={navData.dropdown} />
          {children}
          <Footer />
          <MySideBar
            navigation={navData.navigation}
            dropdown={navData.dropdown}
          />
        </div>
      </body>
    </html>
  );
}
