import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "../styles/globals.css";
import "../styles/normalize.css";
import Navbar from "@/modules/navbar";
import Footer from "@/modules/footer";
import { flattenAttributes, getStrapiData } from "@/utils/utils";
import MySideBar from "@/modules/navbar/components/Sidebar";
import NextBreadcrumb from "@/modules/common/breadcrumbs";
import { ChevronRightIcon } from "lucide-react";

const inter = Ubuntu({
  subsets: ["cyrillic"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navData = await getStrapiData(
    "/api/global?populate[navigation][populate][links]=*&[populate][dropdown][populate][subMenuLinks][populate][country]=true&[populate][dropdown][populate][subMenuLinks][populate][university]=*"
  );

  return (
    <html lang="en">
      <body className={`bg-light dark:bg-dark  ${inter.className}`}>
        <div className="relative w-full h-full text-gray-400">
          <Navbar navigation={navData.navigation} dropdown={navData.dropdown} />
          <NextBreadcrumb
            homeElement={"Home"}
            separator={
              <span className="flex justify-center items-center">
                <ChevronRightIcon size={15} />
              </span>
            }
            activeClasses="text-dark"
            containerClasses="flex py-5 gap-3 mx-16 text-sm "
            listClasses="text-accent hover:text-dark"
            capitalizeLinks
            disabledClasses="cursor-not-allowed "
          />
          {children}
          <Footer />
          <MySideBar
            navigation={navData.navigation}
            dropdown={navData.dropdown}
          />
        </div>
      </body>
    </html>
  );
}
