/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor from "@ckeditor/strapi-plugin-ckeditor/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import calendar from "@offset-dev/strapi-calendar/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import scheduler from "@webbio/strapi-plugin-scheduler/strapi-admin";
import strapiGoogleAuth from "strapi-google-auth/strapi-admin";
import meilisearch from "strapi-plugin-meilisearch/strapi-admin";
import todo from "strapi-plugin-todo/strapi-admin";
import strapiRegenerator from "strapi-regenerator/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,
  plugins: {
    ckeditor: ckeditor,
    "users-permissions": usersPermissions,
    i18n: i18N,
    calendar: calendar,
    graphql: graphql,
    seo: seo,
    scheduler: scheduler,
    "strapi-google-auth": strapiGoogleAuth,
    meilisearch: meilisearch,
    todo: todo,
    "strapi-regenerator": strapiRegenerator,
  },
});
