/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor from "@ckeditor/strapi-plugin-ckeditor/strapi-admin";
import calendar from "@offset-dev/strapi-calendar/strapi-admin";
import strapiNewsletter from "@strapi-newsletter/strapi/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import scheduler from "@webbio/strapi-plugin-scheduler/strapi-admin";
import todo from "strapi-plugin-todo/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    ckeditor: ckeditor,
    calendar: calendar,
    "strapi-newsletter": strapiNewsletter,
    graphql: graphql,
    seo: seo,
    "users-permissions": usersPermissions,
    i18n: i18N,
    scheduler: scheduler,
    todo: todo,
  },
});
